
-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE
-- OR REPLACE VIEW "public"."cloudaccount_k8s_pod_aggregate" AS
-- SELECT
--   ca.id,
--   ca.tenant,
--   (cr.tags ->> 'controllerKind' :: text) AS workload_type,
--   (cr.tags ->> 'controller' :: text) AS workload_name,
--   (cr.tags ->> 'namespace' :: text) AS namespace_name,
--   (cr.tags ->> 'pod' :: text) AS pod_name,
--   s.date AS "timestamp",
--   sum(s.amount) AS pod_cost,
--   avg(
--     CASE
--       WHEN (crm.metric = 'cpuCoreUsageAverage' :: text) THEN crm.value
--       ELSE NULL :: double precision
--     END
--   ) AS cpu_used,
--   avg(
--     CASE
--       WHEN (crm.metric = 'ramByteUsageAverage' :: text) THEN crm.value
--       ELSE NULL :: double precision
--     END
--   ) AS memory_used,
--   avg(
--     CASE
--       WHEN (crm.metric = 'cpuCoreRequestAverage' :: text) THEN crm.value
--       ELSE NULL :: double precision
--     END
--   ) AS cpu_request,
--   avg(
--     CASE
--       WHEN (crm.metric = 'ramByteRequestAverage' :: text) THEN crm.value
--       ELSE NULL :: double precision
--     END
--   ) AS memory_request,
--   avg(
--     CASE
--       WHEN (crm.metric = 'cpuEfficiency' :: text) THEN crm.value
--       ELSE NULL :: double precision
--     END
--   ) AS cpu_efficiency,
--   avg(
--     CASE
--       WHEN (crm.metric = 'ramEfficiency' :: text) THEN crm.value
--       ELSE NULL :: double precision
--     END
--   ) AS ram_efficiency
-- FROM
--   (
--     (
--       (
--         cloud_accounts ca
--         JOIN cloud_resourses cr ON ((cr.account = ca.id))
--       )
--       JOIN spends s ON (
--         (
--           (s.cloud_account = ca.id)
--           AND (s.cloud_resource_id = cr.id)
--         )
--       )
--     )
--     JOIN cloud_resource_metrics crm ON ((crm.cloud_resource_id = cr.id))
--   )
-- WHERE
--   (
--     (ca.account_type = 'kubernetes' :: text)
--     AND ((cr.tags ->> 'controllerKind' :: text) IS NOT NULL)
--     AND (
--       crm.metric = ANY (
--         ARRAY ['cpuCoreUsageAverage'::text, 'ramByteUsageAverage'::text, 'cpuCoreRequestAverage'::text, 'ramByteRequestAverage'::text]
--       )
--     )
--   )
-- GROUP BY
--   ca.id,
--   ca.tenant,
--   (cr.tags ->> 'controllerKind' :: text),
--   (cr.tags ->> 'controller' :: text),
--   (cr.tags ->> 'namespace' :: text),
--   (cr.tags ->> 'pod' :: text),
--   s.date;

-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DROP VIEW "public"."cloudaccount_k8s_pod_aggregate";

-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE VIEW "public"."cloudaccount_k8s_pod_aggregate" AS
--  SELECT ca.id,
--     ca.tenant,
--     (cr.tags ->> 'controllerKind'::text) AS workload_type,
--     (cr.tags ->> 'controller'::text) AS workload_name,
--     (cr.tags ->> 'namespace'::text) AS namespace_name,
--     (cr.tags ->> 'pod'::text) AS pod_name,
--     s.date AS "timestamp",
--     sum(s.amount) AS workload_cost,
--     avg(
--         CASE
--             WHEN (crm.metric = 'cpuCoreUsageAverage'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS cpu_used,
--     avg(
--         CASE
--             WHEN (crm.metric = 'ramByteUsageAverage'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS memory_used,
--     avg(
--         CASE
--             WHEN (crm.metric = 'cpuCoreRequestAverage'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS cpu_request,
--     avg(
--         CASE
--             WHEN (crm.metric = 'ramByteRequestAverage'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS memory_request,
--     avg(
--         CASE
--             WHEN (crm.metric = 'cpuEfficiency'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS cpu_efficiency,
--     avg(
--         CASE
--             WHEN (crm.metric = 'ramEfficiency'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS ram_efficiency
--    FROM (((cloud_accounts ca
--      JOIN cloud_resourses cr ON ((cr.account = ca.id)))
--      JOIN spends s ON (((s.cloud_account = ca.id) AND (s.cloud_resource_id = cr.id))))
--      JOIN cloud_resource_metrics crm ON ((crm.cloud_resource_id = cr.id)))
--   WHERE ((ca.account_type = 'kubernetes'::text) AND ((cr.tags ->> 'controllerKind'::text) IS NOT NULL) AND (crm.metric = ANY (ARRAY['cpuCoreUsageAverage'::text, 'ramByteUsageAverage'::text, 'cpuCoreRequestAverage'::text, 'ramByteRequestAverage'::text])))
--   GROUP BY ca.id, ca.tenant, (cr.tags ->> 'controllerKind'::text), (cr.tags ->> 'controller'::text), (cr.tags ->> 'namespace'::text), (cr.tags ->> 'pod'::text), s.date;

-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE VIEW "public"."cloudaccount_k8s_workload_aggregate" AS
--  SELECT ca.id,
--     ca.tenant,
--     (cr.tags ->> 'controllerKind'::text) AS workload_type,
--     (cr.tags ->> 'controller'::text) AS workload_name,
--     s.date AS "timestamp",
--     sum(s.amount) AS workload_cost,
--     avg(
--         CASE
--             WHEN (crm.metric = 'cpuCoreUsageAverage'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS cpu_used,
--     avg(
--         CASE
--             WHEN (crm.metric = 'ramByteUsageAverage'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS memory_used,
--     avg(
--         CASE
--             WHEN (crm.metric = 'cpuCoreRequestAverage'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS cpu_request,
--     avg(
--         CASE
--             WHEN (crm.metric = 'ramByteRequestAverage'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS memory_request,
--     avg(
--         CASE
--             WHEN (crm.metric = 'cpuEfficiency'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS cpu_efficiency,
--     avg(
--         CASE
--             WHEN (crm.metric = 'ramEfficiency'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS ram_efficiency,
--     count(DISTINCT
--         CASE
--             WHEN ((cr.tags ->> 'pod'::text) IS NOT NULL) THEN (cr.tags ->> 'pod'::text)
--             ELSE NULL::text
--         END) AS pod_count,
--     (cr.tags ->> 'namespace'::text) AS namespace_name
--    FROM (((cloud_accounts ca
--      JOIN cloud_resourses cr ON ((cr.account = ca.id)))
--      JOIN spends s ON (((s.cloud_account = ca.id) AND (s.cloud_resource_id = cr.id))))
--      JOIN cloud_resource_metrics crm ON ((crm.cloud_resource_id = cr.id)))
--   WHERE ((ca.account_type = 'kubernetes'::text) AND ((cr.tags ->> 'controllerKind'::text) IS NOT NULL) AND (crm.metric = ANY (ARRAY['cpuCoreUsageAverage'::text, 'ramByteUsageAverage'::text, 'cpuCoreRequestAverage'::text, 'ramByteRequestAverage'::text])))
--   GROUP BY ca.id, ca.tenant, (cr.tags ->> 'controllerKind'::text), (cr.tags ->> 'controller'::text), (cr.tags ->> 'namespace'::text), s.date;

-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE VIEW "public"."cloudaccount_k8s_workload_aggregate" AS
--  SELECT ca.id,
--     ca.tenant,
--     (cr.tags ->> 'controllerKind'::text) AS workload_type,
--     (cr.tags ->> 'controller'::text) AS workload_name,
--     s.date AS "timestamp",
--     sum(s.amount) AS workload_cost,
--     avg(
--         CASE
--             WHEN (crm.metric = 'cpuCoreUsageAverage'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS cpu_used,
--     avg(
--         CASE
--             WHEN (crm.metric = 'ramByteUsageAverage'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS memory_used,
--     avg(
--         CASE
--             WHEN (crm.metric = 'cpuCoreRequestAverage'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS cpu_request,
--     avg(
--         CASE
--             WHEN (crm.metric = 'ramByteRequestAverage'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS memory_request,
--     avg(
--         CASE
--             WHEN (crm.metric = 'cpuEfficiency'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS cpu_efficiency,
--     avg(
--         CASE
--             WHEN (crm.metric = 'ramEfficiency'::text) THEN crm.value
--             ELSE NULL::double precision
--         END) AS ram_efficiency,
--     count(distinct case when cr.tags ->> 'pod' is not null then cr.tags ->> 'pod' end) as pod_count,
--     (cr.tags ->> 'namespace'::text) AS namespace_name
--    FROM (((cloud_accounts ca
--      JOIN cloud_resourses cr ON ((cr.account = ca.id)))
--      JOIN spends s ON (((s.cloud_account = ca.id) AND (s.cloud_resource_id = cr.id))))
--      JOIN cloud_resource_metrics crm ON ((crm.cloud_resource_id = cr.id)))
--   WHERE ((ca.account_type = 'kubernetes'::text) AND ((cr.tags ->> 'controllerKind'::text) IS NOT NULL) AND (crm.metric = ANY (ARRAY['cpuCoreUsageAverage'::text, 'ramByteUsageAverage'::text, 'cpuCoreRequestAverage'::text, 'ramByteRequestAverage'::text])))
--   GROUP BY ca.id, ca.tenant, (cr.tags ->> 'controllerKind'::text), (cr.tags ->> 'controller'::text), (cr.tags ->> 'namespace'::text), s.date;
