-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO public.recommendation_severity_type (value) SELECT 'Critical' ON CONFLICT DO NOTHING ;
