-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO "public"."auto_playbook_status"("value", "description") VALUES (E'Disabled', E'the auto playbook is in disabled') ON CONFLICT DO NOTHING;
