
INSERT INTO "public"."runbook_action"("attributes", "base_action_configs", "configs", "account_type", "action_name", "description", "internal_identifier", "status", "created_at", "updated_at", "created_by", "id", "library_id", "tenant_id") VALUES ('{"resource_filter":{"resource_type":"compute-instance","context_applicable":true,"resource_mandatory":true,"resource_applicable":false},"applicable_trigger":["schedule"],"applicable_event_type":[]}', '{}', '{}', E'AWS', E'EC2 instance start', E'To start Ec2 instance', E'aws_instance_start', E'ACTIVE', now(), null, null, gen_random_uuid(), E'0e1e7e4c-b09c-4259-81dc-aec51ef45114', null);

INSERT INTO "public"."runbook_action"("attributes", "base_action_configs", "configs", "account_type", "action_name", "description", "internal_identifier", "status", "created_at", "updated_at", "created_by", "id", "library_id", "tenant_id") VALUES ('{"resource_filter":{"resource_type":"compute-instance","context_applicable":true,"resource_mandatory":true,"resource_applicable":false},"applicable_trigger":["schedule"],"applicable_event_type":[]}', '{}', '{}', E'AWS', E'EC2 instance stop', E'To stop Ec2 instance', E'aws_instance_stop', E'ACTIVE', now(), null, null, gen_random_uuid(), E'0e1e7e4c-b09c-4259-81dc-aec51ef45114', null);

INSERT INTO "public"."runbook_action"("attributes", "base_action_configs", "configs", "account_type", "action_name", "description", "internal_identifier", "status", "created_at", "updated_at", "created_by", "id", "library_id", "tenant_id") VALUES ('{"resource_filter":{"resource_type":"db","context_applicable":true,"resource_mandatory":true,"resource_applicable":false},"applicable_trigger":["schedule"],"applicable_event_type":[]}', '{}', '{}', E'AWS', E'RDS instance stop', E'To stop RDS instance', E'aws_rds_instance_stop', E'ACTIVE', now(), null, null, gen_random_uuid(), E'0e1e7e4c-b09c-4259-81dc-aec51ef45114', null);

INSERT INTO "public"."runbook_action"("attributes", "base_action_configs", "configs", "account_type", "action_name", "description", "internal_identifier", "status", "created_at", "updated_at", "created_by", "id", "library_id", "tenant_id") VALUES ('{"resource_filter":{"resource_type":"db","context_applicable":true,"resource_mandatory":true,"resource_applicable":false},"applicable_trigger":["schedule"],"applicable_event_type":[]}', '{}', '{}', E'AWS', E'RDS instance start', E'To start RDS instance', E'aws_rds_instance_start', E'ACTIVE', now(), null, null, gen_random_uuid(), E'0e1e7e4c-b09c-4259-81dc-aec51ef45114', null);

update public.runbook_action set configs = '[]' where configs = '{}';