-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."llm_conversation_history" add column "request_type" text
--  not null;
