-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- update
--     auto_pilot_task
-- set
--     status = 'Skipped'
-- where
--     reason in (
--         'No vertical rightsize changes triggered based on rules provided',
--         'Skipped as allocated is same as recommended',
--         'Recommended and allocated replica are same no need to change'
--     );
