-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- update
--     agent_task
-- set
--     status = 'Timeout'
-- where
--     created_at < (CURRENT_TIMESTAMP - INTERVAL '3600 seconds')
--     and status = 'TODO';
