
CREATE TABLE "public"."auto_pilot_approvals" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "autopilot_id" uuid NOT NULL, "status" text NOT NULL, "created_at" timestamp NOT NULL DEFAULT now(), "updated_at" timestamp, "reviewer_comments" text, "reviewer_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "account_id" uuid NOT NULL, "attributes" jsonb NOT NULL, PRIMARY KEY ("id") , FOREIGN KEY ("reviewer_id") REFERENCES "public"."users"("id") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("tenant_id") REFERENCES "public"."tenant"("id") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("account_id") REFERENCES "public"."cloud_accounts"("id") ON UPDATE restrict ON DELETE restrict, UNIQUE ("id"));COMMENT ON TABLE "public"."auto_pilot_approvals" IS E'approval status for runbook or auto optimize';
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE "public"."auto_pilot_reviewers" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "created_at" timestamp NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, PRIMARY KEY ("id") , FOREIGN KEY ("tenant_id") REFERENCES "public"."tenant"("id") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE restrict ON DELETE restrict, UNIQUE ("id"));COMMENT ON TABLE "public"."auto_pilot_reviewers" IS E'reviewer allowed to approve a autopilot config';
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE "public"."auto_pilot_reviewee" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "created_at" timestamp NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, PRIMARY KEY ("id") , FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE restrict ON DELETE restrict, FOREIGN KEY ("tenant_id") REFERENCES "public"."tenant"("id") ON UPDATE restrict ON DELETE restrict, UNIQUE ("id"));COMMENT ON TABLE "public"."auto_pilot_reviewee" IS E'the users whom auto pilots need to be reviewed';
CREATE EXTENSION IF NOT EXISTS pgcrypto;
