-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."llm_conversation_agent" add column "input_tokens" integer
--  null default '0';
