-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."auto_playbook_task" add column "action_type" text
--  not null default 'agent_task';
