-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."knowledge_graph_node" add column "is_active" boolean
--  not null default 'true';
