INSERT INTO public.recommendation_rule
  (rule_name, category, title, description, service_name, recommendations, mitigations, compliances, "references")
VALUES
  ('aws_native_purchase_reserved_instances', 'RightSizing', 'AWS Purchase Reserved Instances', 'AWS Cost Optimization Hub has identified potential savings by purchasing Reserved Instances. Reserved Instances provide a significant discount compared to On-Demand pricing in exchange for a usage commitment.', 'AWSCostOptimizationHub', '["Review the recommended Reserved Instance purchase and evaluate whether your usage patterns justify the commitment."]'::jsonb, '["Navigate to the AWS Cost Optimization Hub console to review the full recommendation details and purchase Reserved Instances through the AWS Management Console."]'::jsonb, '[]'::jsonb, '["https://docs.aws.amazon.com/cost-management/latest/userguide/ce-ri-recommendations.html"]'::jsonb),
  ('aws_native_purchase_savings_plans', 'RightSizing', 'AWS Purchase Savings Plans', 'AWS Cost Optimization Hub has identified potential savings through Savings Plans. Savings Plans offer flexible pricing in exchange for a commitment to a consistent amount of usage for a 1- or 3-year term.', 'AWSCostOptimizationHub', '["Review the recommended Savings Plan purchase and evaluate whether your compute usage patterns justify the commitment."]'::jsonb, '["Navigate to the AWS Cost Optimization Hub console to review the full recommendation details and purchase Savings Plans through the AWS Management Console."]'::jsonb, '[]'::jsonb, '["https://docs.aws.amazon.com/cost-management/latest/userguide/sp-recommendations.html"]'::jsonb),
  ('aws_native_rightsize', 'RightSizing', 'AWS Right-Size Resource', 'AWS Cost Optimization Hub has identified a resource that is over-provisioned relative to its usage. Right-sizing to a smaller or more appropriate configuration can reduce costs.', 'AWSCostOptimizationHub', '["Review the recommended resource configuration and right-size the resource to match actual usage."]'::jsonb, '["Navigate to the AWS Cost Optimization Hub console to review the full recommendation details and apply the suggested configuration change."]'::jsonb, '[]'::jsonb, '["https://docs.aws.amazon.com/cost-management/latest/userguide/cost-optimization-hub.html"]'::jsonb),
  ('aws_native_stop', 'RightSizing', 'AWS Stop Idle Resource', 'AWS Cost Optimization Hub has identified an idle or underutilized resource that can be stopped to reduce costs.', 'AWSCostOptimizationHub', '["Review the resource utilization and stop or terminate the idle resource if it is no longer needed."]'::jsonb, '["Navigate to the AWS Cost Optimization Hub console to review the full recommendation details and stop the resource."]'::jsonb, '[]'::jsonb, '["https://docs.aws.amazon.com/cost-management/latest/userguide/cost-optimization-hub.html"]'::jsonb),
  ('aws_native_delete', 'RightSizing', 'AWS Delete Unused Resource', 'AWS Cost Optimization Hub has identified an unused resource that can be deleted to eliminate unnecessary costs.', 'AWSCostOptimizationHub', '["Review the resource and delete it if it is confirmed to be unused and no longer needed."]'::jsonb, '["Navigate to the AWS Cost Optimization Hub console to review the full recommendation details and delete the resource."]'::jsonb, '[]'::jsonb, '["https://docs.aws.amazon.com/cost-management/latest/userguide/cost-optimization-hub.html"]'::jsonb),
  ('aws_native_upgrade', 'RightSizing', 'AWS Upgrade Resource', 'AWS Cost Optimization Hub has identified a resource running an older generation that can be upgraded to a newer, more cost-effective generation.', 'AWSCostOptimizationHub', '["Review the recommended upgrade and migrate the resource to the newer generation for better price-performance."]'::jsonb, '["Navigate to the AWS Cost Optimization Hub console to review the full recommendation details and apply the upgrade."]'::jsonb, '[]'::jsonb, '["https://docs.aws.amazon.com/cost-management/latest/userguide/cost-optimization-hub.html"]'::jsonb),
  ('aws_native_migrate_graviton', 'RightSizing', 'AWS Migrate to Graviton', 'AWS Cost Optimization Hub has identified a resource that can be migrated to AWS Graviton processors for better price-performance. Graviton-based instances deliver up to 40% better price-performance.', 'AWSCostOptimizationHub', '["Review application compatibility and migrate the resource to a Graviton-based instance type for improved price-performance."]'::jsonb, '["Navigate to the AWS Cost Optimization Hub console to review the full recommendation details and plan the Graviton migration."]'::jsonb, '[]'::jsonb, '["https://docs.aws.amazon.com/cost-management/latest/userguide/cost-optimization-hub.html"]'::jsonb)
ON CONFLICT (rule_name) DO NOTHING;
