DELETE FROM "public"."feature_flag" WHERE "feature_id" = 'EVENT_INVESTIGATION_SKIP_SERVICE_LABEL_CHECK';
DELETE FROM "public"."feature" WHERE "value" = 'EVENT_INVESTIGATION_SKIP_SERVICE_LABEL_CHECK';
