#   feat(ui): Add `Button` component
#   ^    ^    ^
#   |    |    |__ Subject
#   |    |_______ Scope
#   |____________ Type

titleOnly: true
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - chore
  - revert
  - ci
  - infra
  - release
scopes:
  - autopilot
  - workflow
  - ml
  - llm
  - notifications
  - ui
  - tickets
  - relay
  - collector
  - observability
  - deps
  - NB-\d+
  - nb-\d+
requireScope: true

#subjectPattern: ^(?![A-Z]).+$