{{- if .Values.temporal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nudgebee-temporal
data:
  password: {{ default "password" .Values.nudgebee_secret.TEMPORAL_DB_PASSWORD | b64enc | quote }}
type: Opaque
{{- end }}
