{{- if and .Values.redis.enabled (or (not .Values.redis.auth.existingSecret) (eq .Values.redis.auth.existingSecret "redis")) }}
apiVersion: v1
kind: Secret
metadata:
  name: redis
data:
  redis-password: {{ default "password" .Values.nudgebee_secret.REDIS_USER_PASSWORD | b64enc | quote }}
type: Opaque
{{- end }}
