{{- if and .Values.postgresql.enabled (or (not .Values.postgresql.auth.existingSecret) (eq .Values.postgresql.auth.existingSecret "postgresql")) }}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
data:
  postgres-password: {{ default "password" .Values.nudgebee_secret.POSTGRES_PASSWORD | b64enc | quote }}
type: Opaque
{{- end }}
