{{- if and .Values.nudgebee_registry_secret.enabled (or (not .Values.nudgebee_registry_secret.existingSecretName) (eq .Values.nudgebee_registry_secret.existingSecretName "nudgebee-registry-secret")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ "nudgebee-registry-secret" | quote }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
{{- end }}
