{{- if and .Values.clickhouse.enabled (or (not .Values.clickhouse.auth.existingSecret) (eq .Values.clickhouse.auth.existingSecret "clickhouse")) }}
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse
data:
  admin-password: {{ default "password" .Values.nudgebee_secret.CLICKHOUSE_PASSWORD | b64enc | quote }}
type: Opaque
{{- end }}
