{{- if and .Values.rabbitmq.enabled (or (not .Values.rabbitmq.auth.existingPasswordSecret) (eq .Values.rabbitmq.auth.existingPasswordSecret "rabbitmq")) }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
data:
  rabbitmq-erlang-cookie: {{ default "Q1nAboy8GxEgOjEfOb9tvsBGRZamqMRd" .Values.nudgebee_secret.RABBIT_MQ_ERLANG_COOKIE | b64enc | quote }}
  rabbitmq-password: {{ default "password" .Values.nudgebee_secret.RABBIT_MQ_PASSWORD | b64enc | quote }}
type: Opaque
{{- end }}
