apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: workflow-server-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-server-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "workflow-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: workflow-server-role
  apiGroup: rbac.authorization.k8s.io
