{{- if .Values.dualMode.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s_collector.fullname" . }}-worker
  labels:
    {{- include "k8s_collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- with (.Values.dualMode.worker.service.annotations | default .Values.service.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.dualMode.worker.service.type | default .Values.service.type }}
  ports:
    {{- if .Values.dualMode.worker.service.ports }}
    {{- toYaml .Values.dualMode.worker.service.ports | nindent 4 }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "k8s_collector.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
{{- end }}