import { colors } from 'src/utils/colors';
export const allClustersTableheaders = [
  'Cluster name',
  'Node ',
  'Pods Failures',
  'Total CPU',
  'Max CPU',
  'Total Mem ',
  'Max Mem',
  'MTD Cost',
  'Bee Score',
  '',
];

export const topClustersTableHeaders = [
  'Cluster name',
  'Total cost',
  'Compute cost',
  'Mem cost',
  'Forecast cost',
  'Compute cost',
  'CPU prov. cost',
  'CPU cost/hr',
  'Mem cost/hr',
];

export const allNodesTableHeaders = ['ID/Name', 'Created', 'Type', 'Pricing', 'Price', 'CPU cost', 'CPU', 'Memory', 'Status'];
export const topWorkloadsTableHeaders = ['ID Name', 'Created', 'Type', 'Pricing', 'Price', 'CPU Cost', 'CPU', 'Memory', 'Status', ''];
export const topNamespaceTableHeaders = ['Date', 'Workloads', 'CPU', 'GiB', 'CPU', 'GiB', 'Total cost', ''];
export const podsTableHeaders = ['Date', 'Pods', 'CPU', 'GiB', 'CPU', 'GiB', 'Total cost', ''];
export const clusterIssuesHeader = ['Pod Name', 'Status', 'Message', 'Namespace', 'Type', 'Age', 'Severity', ''];
export const podExceptionHeader = ['Pod Name', 'Status', 'Controlled By', 'Message', 'Namespace', 'Restart Count', 'Age', 'Severity', ''];
export const nodeExceptionHeader = [
  'Node Name',
  { name: 'Message', width: '30%' },
  { name: 'Type', width: '5%' },
  'Status',
  { name: 'Age', width: '5%' },
  'Severity',
];

export const podsSummaryTableHeaders = ['Date', 'Pods', 'Cost per Pod', 'CPU', 'GiB', 'CPU', 'GiB', 'Total cost'];
export const podsRestartHeader = [
  'Workload Name',
  'Pod Name',
  '# of Restart',
  'Max Utilization',
  'Max Required',
  'CPU Limit',
  'Avg Required',
  'Max Utilization',
  'Max Required',
  'Memory Limit',
  'Avg Required',
  '',
];
export const podsUtilizationHeader = [
  'Workload Name',
  'Pod Name',
  'Max Utilization',
  'Max Required',
  'CPU Limit',
  'Avg Required',
  'Max Utilization',
  'Max Required',
  'Memory Limit',
  'Avg Required',
];

export const rightSizingHeader = ['Name', 'Namespace', 'Kind', 'CPU Req/Recommended', 'Memory Req/Recommended', 'Savings', '', ''];
//=============|  Upper Header  |=============
export const allClustersTableUpperHeaders = [
  { text: '' },
  { text: '' },
  { text: '' },
  { text: 'Utilization', colSpan: 4, backgroundColor: colors.background.infoGraphic },
  { text: '' },
];
export const topClustersTableUpperHeaders = [
  { text: '' },
  { text: 'MTD', colSpan: 3, backgroundColor: colors.background.infoGraphic },
  { text: '' },
  { text: 'Last 7 days', colSpan: 4, backgroundColor: colors.background.null },
];

export const topWorkloadsTableUpperHeaders = [
  { text: '' },
  { text: '' },
  { text: 'Avg requested', colSpan: 3, backgroundColor: colors.background.infoGraphic },
  { text: '', colSpan: 5 },
];

export const workloadSortingTableUpperHeaders = [
  { text: '' },
  { text: '' },
  { text: 'Avg requested per resource', colSpan: 3, backgroundColor: colors.background.infoGraphic },
  { text: 'Last 7 days', colSpan: 5, backgroundColor: colors.background.null },
];

export const topNamespaceTableUpperHeaders = [
  { text: '' },
  { text: '' },
  { text: 'Avg requested per resource', colSpan: 2, backgroundColor: colors.background.infoGraphic },
  { text: 'Total cost per resource', colSpan: 2, backgroundColor: colors.background.null },
  { text: '' },
];

export const podsSummaryTableUpperHeaders = [{ text: '' }, ...topNamespaceTableUpperHeaders];

//=============|  Table Data  |=============

export const kubernetesTableData = [
  {
    id: 1,
    name: 'All',
    region: 'US-East-1',
    podName: 'frontend-app',
    message: 'Fail to pull image',
    namespace: 'name-space-name-x',
    date: '2023-06-08',
    node: { demand: 325, fallback: 25, spot: 100 },
    computeCost: { demand: 325, fallback: 25, spot: 100 },
    podsCluster: { scheduled: 325, unScheduled: 25 },
    workloads: 1242,
    totalCost: 1242,
    pods: 382.13,
    podsCost: 72.13,
    cpu: 364,
    usedCpuPercentage: 46,
    usedCpuValue: 46,
    memory: 430,
    usedMemoryPercentage: 76,
    usedMemoryValue: 23,
    dailySpend: 32246,
    currMonthlySpend: 4248,
    yearlySavings: 4248,
    connected: '1 month ago',
    type: 'Event',
    age: '14min',
    status: 'Pending',
    controlledBy: 'Job-namesa223',
    nodeOS: 'AWSLinux',
    health: 14,
    instanceType: 'c5.2xaLarge',
    pricing: 'Spot',
  },
  {
    id: 2,
    name: 'Amazon Elastic Compute Cloud - Compute',
    region: 'US-East-1',
    podName: 'frontend-app',
    namespace: 'name-space-name-x',
    message: 'Fail to pull image',
    date: '2023-06-08',
    node: { demand: 200, fallback: 125, spot: 95 },
    computeCost: { demand: 200, fallback: 125, spot: 95 },
    podsCluster: { scheduled: 200, unScheduled: 125 },
    workloads: 1242,
    totalCost: 1242,
    pods: 412.13,
    podsCost: 72.13,
    cpu: 2.6,
    usedCpuPercentage: 15,
    usedCpuValue: 15,
    memory: 130,
    usedMemoryPercentage: 15,
    usedMemoryValue: 15,
    dailySpend: 32215,
    currMonthlySpend: 4218,
    yearlySavings: 4218,
    connected: '1 month ago',
    type: 'Event',
    age: '14min',
    status: 'Running',
    controlledBy: 'Job-namesa223',
    nodeOS: 'AWSLinux',
    health: 14,
    instanceType: 'c5.2xaLarge',
    pricing: 'Spot',
  },
  {
    id: 3,
    name: 'Amazon Elastic Compute for kubernetes',
    region: 'US-East-1',
    namespace: 'name-space-name-x',
    date: '2023-06-08',
    podName: 'frontend-app',
    message: 'Fail to pull image',
    node: { demand: 325, fallback: 305, spot: 400 },
    computeCost: { demand: 325, fallback: 305, spot: 400 },
    podsCluster: { scheduled: 325, unScheduled: 305 },
    workloads: 1242,
    totalCost: 1242,
    pods: 275,
    podsCost: 75,
    cpu: 6,
    usedCpuPercentage: 15,
    usedCpuValue: 15,
    memory: 130,
    usedMemoryPercentage: 15,
    usedMemoryValue: 15,
    dailySpend: 32215,
    currMonthlySpend: 4218,
    yearlySavings: 4218,
    connected: '1 month ago',
    type: 'Event',
    age: '14min',
    status: 'Running',
    controlledBy: 'Job-namesa223',
    nodeOS: 'AWSLinux',
    health: 14,
    instanceType: 'c5.2xaLarge',
    pricing: 'Spot',
  },
  {
    id: 4,
    name: 'Amazon Elastic Compute',
    region: 'US-East-1',
    namespace: 'name-space-name-x',
    date: '2023-06-08',
    node: { demand: 10, fallback: 25, spot: 8 },
    computeCost: { demand: 10, fallback: 25, spot: 8 },
    podsCluster: { scheduled: 10, unScheduled: 25 },
    workloads: 1242,
    totalCost: 1242,
    pods: 75,
    podName: 'frontend-app',
    message: 'Fail to pull image',
    podsCost: 7,
    cpu: 6.6,
    usedCpuPercentage: 15,
    usedCpuValue: 15,
    memory: 130,
    usedMemoryPercentage: 15,
    usedMemoryValue: 15,
    dailySpend: 32215,
    currMonthlySpend: 4218,
    yearlySavings: 4218,
    connected: '1 month ago',
    type: 'Event',
    age: '14min',
    status: 'Running',
    controlledBy: 'Job-namesa223',
    nodeOS: 'AWSLinux',
    health: 14,
    instanceType: 'c5.2xaLarge',
    pricing: 'Spot',
  },
  {
    id: 5,
    name: 'AWS',
    region: 'US-East-1',
    namespace: 'name-space-name-x',
    date: '2023-06-08',
    node: { demand: 20, fallback: 65, spot: 35 },
    computeCost: { demand: 20, fallback: 65, spot: 35 },
    podsCluster: { scheduled: 20, unScheduled: 65 },
    workloads: 1242,
    totalCost: 1242,
    pods: 290,
    podName: 'frontend-app',
    message: 'Fail to pull image',
    podsCost: 70,
    cpu: 5,
    usedCpuPercentage: 15,
    usedCpuValue: 15,
    memory: 130,
    usedMemoryPercentage: 15,
    usedMemoryValue: 15,
    dailySpend: 32215,
    currMonthlySpend: 4218,
    yearlySavings: 4218,
    connected: '1 month ago',
    type: 'Event',
    age: '14min',
    status: 'Running',
    controlledBy: 'Job-namesa223',
    nodeOS: 'AWSLinux',
    health: 14,
    instanceType: 'c5.2xaLarge',
    pricing: 'Spot',
  },
  {
    id: 6,
    name: 'All',
    region: 'US-East-1',
    namespace: 'name-space-name-x',
    date: '2023-06-08',
    node: { demand: 325, fallback: 25, spot: 100 },
    computeCost: { demand: 325, fallback: 25, spot: 100 },
    podsCluster: { scheduled: 325, unScheduled: 25 },
    workloads: 1242,
    totalCost: 1242,
    pods: 382.13,
    podName: 'frontend-app',
    message: 'Fail to pull image',
    podsCost: 72.13,
    cpu: 364,
    usedCpuPercentage: 46,
    usedCpuValue: 46,
    memory: 430,
    usedMemoryPercentage: 46,
    usedMemoryValue: 46,
    dailySpend: 32246,
    currMonthlySpend: 4248,
    yearlySavings: 4248,
    connected: '1 month ago',
    type: 'Event',
    age: '14min',
    status: 'Running',
    controlledBy: 'Job-namesa223',
    nodeOS: 'AWSLinux',
    health: 14,
    instanceType: 'c5.2xaLarge',
    pricing: 'Spot',
  },
  {
    id: 7,
    name: 'Amazon Elastic Compute Cloud - Compute',
    region: 'US-East-1',
    namespace: 'name-space-name-x',
    date: '2023-06-08',
    node: { demand: 200, fallback: 125, spot: 10 },
    computeCost: { demand: 200, fallback: 125, spot: 10 },
    podsCluster: { scheduled: 200, unScheduled: 125 },
    workloads: 1242,
    totalCost: 1242,
    pods: 412.13,
    podName: 'frontend-app',
    message: 'Fail to pull image',
    podsCost: 72.13,
    cpu: 2.6,
    usedCpuPercentage: 15,
    usedCpuValue: 15,
    memory: 130,
    usedMemoryPercentage: 15,
    usedMemoryValue: 15,
    dailySpend: 32215,
    currMonthlySpend: 4218,
    yearlySavings: 4218,
    connected: '1 month ago',
    type: 'Event',
    age: '14min',
    status: 'Pending',
    controlledBy: 'Job-namesa223',
    nodeOS: 'AWSLinux',
    health: 14,
    instanceType: 'c5.2xaLarge',
    pricing: 'Spot',
  },
  {
    id: 8,
    name: 'Amazon Elastic Compute for kubernetes',
    region: 'US-East-1',
    namespace: 'name-space-name-x',
    date: '2023-06-08',
    node: { demand: 325, fallback: 305, spot: 400 },
    computeCost: { demand: 325, fallback: 305, spot: 400 },
    podsCluster: { scheduled: 325, unScheduled: 305 },
    workloads: 1242,
    totalCost: 1242,
    pods: 275,
    podName: 'frontend-app',
    message: 'Fail to pull image',
    podsCost: 75,
    cpu: 6,
    usedCpuPercentage: 15,
    usedCpuValue: 15,
    memory: 130,
    usedMemoryPercentage: 15,
    usedMemoryValue: 15,
    dailySpend: 32215,
    currMonthlySpend: 4218,
    yearlySavings: 4218,
    connected: '1 month ago',
    type: 'Event',
    age: '14min',
    status: 'Pending',
    controlledBy: 'Job-namesa223',
    nodeOS: 'AWSLinux',
    health: 14,
    instanceType: 'c5.2xaLarge',
    pricing: 'Spot',
  },
  {
    id: 9,
    name: 'Amazon Elastic Compute',
    region: 'US-East-1',
    namespace: 'name-space-name-x',
    date: '2023-06-08',
    node: { demand: 10, fallback: 25, spot: 8 },
    computeCost: { demand: 10, fallback: 25, spot: 8 },
    podsCluster: { scheduled: 10, unScheduled: 25 },
    workloads: 1242,
    totalCost: 1242,
    pods: 75,
    podName: 'frontend-app',
    message: 'Fail to pull image',
    podsCost: 7,
    cpu: 6.6,
    usedCpuPercentage: 15,
    usedCpuValue: 15,
    memory: 130,
    usedMemoryPercentage: 15,
    usedMemoryValue: 15,
    dailySpend: 32215,
    currMonthlySpend: 4218,
    yearlySavings: 4218,
    connected: '1 month ago',
    type: 'Event',
    age: '14min',
    status: 'Pending',
    controlledBy: 'Job-namesa223',
    nodeOS: 'AWSLinux',
    health: 14,
    instanceType: 'c5.2xaLarge',
    pricing: 'Spot',
  },
  {
    id: 10,
    name: 'AWS page 2',
    region: 'US-East-1',
    namespace: 'name-space-name-x',
    date: '2023-06-08',
    node: { demand: 20, fallback: 65, spot: 35 },
    computeCost: { demand: 20, fallback: 65, spot: 35 },
    podsCluster: { scheduled: 20, unScheduled: 65 },
    workloads: 1242,
    totalCost: 1242,
    pods: 290,
    podName: 'frontend-app',
    message: 'Fail to pull image',
    podsCost: 70,
    cpu: 5,
    usedCpuPercentage: 15,
    usedCpuValue: 15,
    memory: 130,
    usedMemoryPercentage: 15,
    usedMemoryValue: 15,
    dailySpend: 32215,
    currMonthlySpend: 4218,
    yearlySavings: 4218,
    connected: '1 month ago',
    type: 'Event',
    age: '14min',
    status: 'Pending',
    controlledBy: 'Job-namesa223',
    nodeOS: 'AWSLinux',
    health: 14,
    instanceType: 'c5.2xaLarge',
    pricing: 'Spot',
  },
  {
    id: 11,
    name: 'AWS page 3',
    region: 'US-East-1',
    namespace: 'name-space-name-x',
    date: '2023-06-08',
    node: { demand: 20, fallback: 65, spot: 35 },
    computeCost: { demand: 20, fallback: 65, spot: 35 },
    podsCluster: { scheduled: 20, unScheduled: 65 },
    workloads: 1242,
    totalCost: 1242,
    pods: 290,
    podName: 'frontend-app',
    message: 'Fail to pull image',
    podsCost: 70,
    cpu: 5,
    usedCpuPercentage: 15,
    usedCpuValue: 15,
    memory: 130,
    usedMemoryPercentage: 15,
    usedMemoryValue: 15,
    dailySpend: 32215,
    currMonthlySpend: 4218,
    yearlySavings: 4218,
    connected: '1 month ago',
    type: 'Event',
    age: '14min',
    status: 'Pending',
    controlledBy: 'Job-namesa223',
    nodeOS: 'AWSLinux',
    health: 14,
    instanceType: 'c5.2xaLarge',
    pricing: 'Spot',
  },
];
