apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rag-server.fullname" . }}
  labels:
    {{- include "rag-server.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rag-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "rag-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with (( default .Values.global.imagePullSecrets .Values.imagePullSecrets )) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rag-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initCheckEnabled | default true }}
      initContainers:
        - name: db-check
          image: {{ .Values.global.initImages.postgres }}
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', 'until pg_isready -h $(echo "$APP_DATABASE_URL" | sed "s/.*@\(.*\):.*/\1/") -U $(echo "$APP_DATABASE_URL" | sed "s/.*:\/\/\([^:]*\):.*/\1/"); do echo "Waiting for PostgreSQL to be ready..."; sleep 2; done;' ]
          envFrom:
            - secretRef:
                name: {{ include "nudgebee.secretName" . | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "imageName" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/app/entrypoint.sh", "web" ]
          envFrom:
            - secretRef:
                name: {{ include "nudgebee.secretName" . | quote }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.serverPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
