/**
 * Default CSS design tokens as a flat JS object.
 * Used for runtime CSS variable injection and as the source-of-truth
 * for the default theme values.
 *
 * Keys must match the CSS custom property names in theme-tokens.css.
 */
export const DEFAULT_CSS_TOKENS: Record<string, string> = {
  // ── Top-level Colors ──
  '--nb-color-primary': '#2563EB',
  '--nb-color-white': '#FFFFFF',
  '--nb-color-black': '#000000',
  '--nb-color-secondary-default': '#374151',
  '--nb-color-secondary-dark': '#9F9F9F',
  '--nb-color-tertiary': '#737373',
  '--nb-color-nudgebee-main': '#FACF39',
  '--nb-color-sidebar-indicator': '#FACF39',
  '--nb-color-success': '#16A34A',
  '--nb-color-error': '#DC2626',
  '--nb-color-error-text': '#FF1744',
  '--nb-color-switch-icon-color': '#374151',
  '--nb-color-icon-color': '#D0D0D0',
  '--nb-color-switch-icon': '#DBEAFE',
  '--nb-color-cluster-indicator': '#4ADE80',
  '--nb-color-yellow': '#EAB308',
  '--nb-color-edit-icon': '#FCA5A5',
  '--nb-color-highest': '#EF4444',
  '--nb-color-high': '#ea3d3d',
  '--nb-color-medium': '#EAB308',
  '--nb-color-low': '#3498DB',
  '--nb-color-lowest': '#22C55E',
  '--nb-color-lowest-light': '#BBF7D0',
  '--nb-color-na': '#a2a2a2',
  '--nb-color-to-do': '#93C5FD',
  '--nb-color-done': '#86EFAC',
  '--nb-color-in-progress': '#FDE047',
  '--nb-color-open': '#c971ff',
  '--nb-color-critical': '#c00000',
  '--nb-color-info': '#3B82F6',
  '--nb-color-debug': 'gray',
  '--nb-color-ok': '#23D160',
  '--nb-color-firing': '#EF5350',
  '--nb-color-purple': 'purple',
  '--nb-color-dark-primary': '#1F61A4',

  // ── Text Colors ──
  '--nb-text-primary-dark': '#3B82F6',
  '--nb-text-grey-dark': '#646464',
  '--nb-text-null': '#808080',
  '--nb-text-yellow-label': '#EAB308',
  '--nb-text-orange-label': '#FFA500',
  '--nb-text-disabled-input': '#a0a0a0',
  '--nb-text-delete': '#FCA5A5',
  '--nb-text-red': 'red',
  '--nb-text-checkbox-label': '#506386',
  '--nb-text-primary-light': '#60A5FA',
  '--nb-text-divider': '#EBEBEB',
  '--nb-text-last-sync': '#B9B9B9',
  '--nb-text-currency-primary-dark': '#2F4267',
  '--nb-text-pagination': '#294781',
  '--nb-text-line-chart': '#5D5FEF',
  '--nb-text-availability': '#9E9E9E',
  '--nb-text-number-component': '#313131',
  '--nb-text-green': 'green',
  '--nb-text-trace-red': 'rgba(255, 99, 132, 0.2)',
  '--nb-text-trace-blue': 'rgba(54, 162, 235, 0.2)',
  '--nb-text-trace-yellow': 'rgba(255, 206, 86, 0.2)',
  '--nb-text-trace-green': 'rgba(75, 192, 192, 0.2)',
  '--nb-text-trace-purple': 'rgba(153, 102, 255, 0.2)',
  '--nb-text-trace-orange': 'rgba(255, 159, 64, 0.2)',
  '--nb-text-trace-gray': 'rgba(199, 199, 199, 0.2)',
  '--nb-text-trace-cyan': 'rgba(0, 255, 255, 0.2)',
  '--nb-text-trace-magenta': 'rgba(255, 0, 255, 0.2)',
  '--nb-text-trace-teal': 'rgba(0, 128, 128, 0.2)',
  '--nb-text-trace-lime': 'rgba(191, 255, 0, 0.2)',
  '--nb-text-trace-brown': 'rgba(165, 42, 42, 0.2)',
  '--nb-text-trace-pink': 'rgba(255, 105, 180, 0.2)',
  '--nb-text-trace-navy': 'rgba(0, 0, 128, 0.2)',
  '--nb-text-trace-gold': 'rgba(255, 215, 0, 0.2)',
  '--nb-text-trace-olive': 'rgba(128, 128, 0, 0.2)',
  '--nb-text-trace-dark-gray': 'rgba(100, 100, 100, 0.2)',
  '--nb-text-dark-gray': 'darkgray',
  '--nb-text-bar-chart': '#4C7EDE',
  '--nb-text-service-map': '#f00',
  '--nb-text-ios-slider': '#007bff',
  '--nb-text-ios-slider-dark': '#0a84ff',
  '--nb-text-service-map-green': '#2BDCA2',
  '--nb-text-service-map-skyblue': '#96c2fd',
  '--nb-text-service-map-blue': 'blue',
  '--nb-text-low': '#AEA124',
  '--nb-text-sidebar': '#1B2D4A',
  '--nb-text-tertiary-medium': '#D0D0D0',
  '--nb-text-ask-nudgebee-welcome': '#314E7D',
  '--nb-text-ask-nudgebee-username': '#3B71C8',
  '--nb-text-nudgebee-response': '#064B8F',
  '--nb-text-nudgebee-suggestion': '#4B5563',
  '--nb-text-response-list': '#4a5568',
  '--nb-text-search-placeholder': '#C2C6CF',
  '--nb-text-purple-label': '#7B1FA2',
  '--nb-text-orange-label-dark': '#E65100',
  '--nb-text-mid': '#687D95',
  '--nb-text-signin-dark': '#000522',
  '--nb-text-dark': '#2B333A',
  '--nb-text-tertiary-light': '#A3A3A3',
  '--nb-text-quaternary': '#9CA3AF',
  '--nb-text-disabled': '#D1D5DB',
  '--nb-text-tab-group-label': '#5C5C5C',
  '--nb-text-tab-group-arrow': '#BDBDBD',
  '--nb-text-warning-text': '#92400E',
  '--nb-text-on-yellow': '#000000',
  '--nb-text-warning-hover': '#78350F',
  '--nb-text-debug': 'gray',
  '--nb-text-info-dark': '#1E40AF',

  // ── Background Colors ──
  '--nb-bg-primary': '#2563EB',
  '--nb-bg-secondary': '#374151',
  '--nb-bg-tertiary': '#737373',
  '--nb-bg-tertiary-medium': '#D0D0D0',
  '--nb-bg-tertiary-light': '#F3F3F3',
  '--nb-bg-tertiary-lightest': '#F3F3F3',
  '--nb-bg-tertiary-lightestest': '#f8f8f8',
  '--nb-bg-tertiary-lightestestest': '#f9f9f9',
  '--nb-bg-white': '#FFFFFF',
  '--nb-bg-black': '#000000',
  '--nb-bg-sidebar': '#1B2D4A',
  '--nb-bg-secondary-dark': '#9F9F9F',
  '--nb-bg-home': '#FFFFFF',
  '--nb-bg-ask-nudgebee-page': '#FFFFFF',
  '--nb-bg-pages': '#F7F7F7',
  '--nb-bg-active-button-color': '#D9D9D933',
  '--nb-bg-primary-light': '#BFDBFE',
  '--nb-bg-primary-lightest': '#EFF6FF',
  '--nb-bg-error-light': '#FECACA',
  '--nb-bg-transparent': 'transparent',
  '--nb-bg-table-header': '#EEF3FF',
  '--nb-bg-null': '#f6f3f3',
  '--nb-bg-yellow-label': '#FEFCE8',
  '--nb-bg-critical-red': '#E95252',
  '--nb-bg-blue-label': '#E6F1FF',
  '--nb-bg-green-label': 'linear-gradient(95deg, #E5FFED 7.65%, #F0FFF4 103.54%)',
  '--nb-bg-light-red-label': 'linear-gradient(95deg, #FFEAEA 7.65%, #FFF0F0 103.54%)',
  '--nb-bg-input': '#f0f0f0',
  '--nb-bg-error': '#DC2626',
  '--nb-bg-integration-card': '#FFFFFF',
  '--nb-bg-switch-track-dark': '#2ECA45',
  '--nb-bg-switch-track-light': '#65C466',
  '--nb-bg-switch-track-lightest': '#20B684',
  '--nb-bg-switch-thumb': '#33cf4d',
  '--nb-bg-accordion-summary': '#FEF2F2',
  '--nb-bg-active-anchor-button': '#E6F1FF',
  '--nb-bg-active-tab': '#FEE2E2',
  '--nb-bg-active-tab-indicator': '#F87171',
  '--nb-bg-anchor-active-tab': '#DBEAFE',
  '--nb-bg-primary-dark': '#3B82F6',
  '--nb-bg-tab-indicator': '#F87171',
  '--nb-bg-summary-block': '#E3FFEF',
  '--nb-bg-cost-block': '#F8FFFA',
  '--nb-bg-total-recommendation': '#F3F6FD',
  '--nb-bg-red': 'red',
  '--nb-bg-recommendation-chart': '#F6FAFF',
  '--nb-bg-toggle': '#EFF5FF',
  '--nb-bg-ticket-description': '#f9f9f9',
  '--nb-bg-button-tab': '#EDF2FB',
  '--nb-bg-info-graphic': '#f3f8ff',
  '--nb-bg-toggle-icon-btn': '#FFFFFF',
  '--nb-bg-toggle-icon-btn-hover': '#EDF2FB',
  '--nb-bg-code-mirror': '#f5f5f5',
  '--nb-bg-react-flow': '#eee',
  '--nb-bg-title-underline': 'rgba(49, 98, 208, 0.4)',
  '--nb-bg-medium': '#FFF1F1',
  '--nb-bg-low': '#FFFCE5',
  '--nb-bg-warning': '#f0ac5b',
  '--nb-bg-light-box': '#F9FFFB',
  '--nb-bg-collapseable-card': '#F4F9FF',
  '--nb-bg-conversation-card': '#FBFBFB',
  '--nb-bg-selected-conversation': '#D3D3D3',
  '--nb-bg-suggestion-card': '#F9FAFB',
  '--nb-bg-suggestion-card-hover': '#F3F4F6',
  '--nb-bg-nubi-question': '#F6F6F6',
  '--nb-bg-nubi-hover': '#FFFCDF',
  '--nb-bg-shimmer-base': '#F1F5F9',
  '--nb-bg-shimmer-highlight': '#F8FAFC',
  '--nb-bg-purple-label': '#F3E5F5',
  '--nb-bg-orange-label': '#FFF3E0',
  '--nb-bg-brand-button': '#FED931',
  '--nb-bg-brand-button-hover': '#F0CB20',
  '--nb-bg-tab-primary-selected': '#414F66',
  '--nb-bg-warning-light': '#FFFBEB',
  '--nb-bg-warning-button': '#FEF3C7',
  '--nb-bg-warning-button-hover': '#FDE68A',
  '--nb-bg-warning-lightest': '#FEF9C3',

  // ── Border Colors ──
  '--nb-border-primary': '#3B82F6',
  '--nb-border-vertical': '#EBEBEB',
  '--nb-border-primary-light': '#BFDBFE',
  '--nb-border-primary-lightest': '#60A5FA',
  '--nb-border-tertiary': '#BFDBFE',
  '--nb-border-secondary-light': '#EBEBEB',
  '--nb-border-secondary-lightest': '#E0E0E0',
  '--nb-border-quadrant': '#3B82F6',
  '--nb-border-error-light': '#FECACA',
  '--nb-border-insight-card': '#FFDC9C',
  '--nb-border-secondary': '#D0D0D0',
  '--nb-border-success': '#4ADE80',
  '--nb-border-error': '#F83435',
  '--nb-border-error-outline': '#d32f2f',
  '--nb-border-primary-dark': 'rgba(49, 98, 208, 0.30)',
  '--nb-border-cpu-limit': '#EF4444',
  '--nb-border-cpu-recommendation': '#16A34A',
  '--nb-border-cpu-requested': '#3B82F6',
  '--nb-border-logo': '#FACF39',
  '--nb-border-logo-light': '#FDECB0',
  '--nb-border-cpu-usage': '#FFA500',
  '--nb-border-memory-limit': '#EF4444',
  '--nb-border-memory-recommendation': '#16A34A',
  '--nb-border-memory-requested': '#3B82F6',
  '--nb-border-memory-usage': '#FFA500',
  '--nb-border-summary-block': '#B9B9B9',
  '--nb-border-ticket-description': '#ddd',
  '--nb-border-button-tab': '#364193',
  '--nb-border-tertiary-lightest': '#F3F3F3',
  '--nb-border-paper-outline': '#FCA5A5',
  '--nb-border-white': '#FFFFFF',
  '--nb-border-query-autocomplete': '#7A88A4',
  '--nb-border-input': '#cecece',
  '--nb-border-autocomplete-option': '#e0e0e0',
  '--nb-border-value-with-left-border': '#16243E',
  '--nb-border-conversation-card': '#6A7485',
  '--nb-border-nudgebee-suggestion': '#E5E7EB',
  '--nb-border-nudgebee-suggestion-hover': '#D1D5DB',
  '--nb-border-warning': '#F59E0B',

  // ── Button Colors ──
  '--nb-btn-primary': '#3B82F6',
  '--nb-btn-primary-hover': '#2563EB',
  '--nb-btn-primary-text': '#FFFFFF',
  '--nb-btn-primary-disabled': '#BFDBFE',
  '--nb-btn-primary-disabled-text': '#ffffff',
  '--nb-btn-secondary': '#FFFFFF',
  '--nb-btn-secondary-text': '#737373',
  '--nb-btn-secondary-hover': '#F8F8F8',
  '--nb-btn-secondary-border': '#d7d7d7',
  '--nb-btn-secondary-hover-border': '#D0D0D0',
  '--nb-btn-secondary-disabled': '#F8F8F8',
  '--nb-btn-secondary-disabled-text': '#D0D0D0',
  '--nb-btn-secondary-disabled-border': '#EBEBEB',
  '--nb-btn-tertiary-border': '#60A5FA',
  '--nb-btn-tertiary': '#FFFFFF',
  '--nb-btn-tertiary-text': '#3B82F6',
  '--nb-btn-tertiary-hover': '#EFF6FF',
  '--nb-btn-tertiary-hover-border': '#60A5FA',
  '--nb-btn-tertiary-disabled': '#FFFFFF',
  '--nb-btn-tertiary-disabled-text': '#93C5FD',
  '--nb-btn-tertiary-disabled-border': '#BFDBFE',

  // ── Shadow ──
  '--nb-shadow-card': '0px 4px 20px -1px rgba(229, 229, 229, 0.4), 0px 2px 20px 0px rgb(233, 233, 233)',
  '--nb-shadow-tab': '0px 4px 10px -1px rgba(229, 229, 229, 0.2), 0px 2px 10px 0px rgb(233, 233, 233)',

  // ── Status Badge Colors ──
  '--nb-status-blue-bg': '#E3F2FD',
  '--nb-status-blue-text': '#1565C0',
  '--nb-status-green-bg': '#E8F5E9',
  '--nb-status-green-text': '#2E7D32',
  '--nb-status-red-bg': '#FFEBEE',
  '--nb-status-red-text': '#C62828',

  // ── MUI Theme Palette ──
  '--nb-mui-primary': '#27429C',
  '--nb-mui-success': '#00C853',
  '--nb-mui-success-contrast': '#ffffff',
  '--nb-mui-error': '#FF1744',
  '--nb-mui-error-contrast': '#ffffff',
  '--nb-mui-radio-unchecked': '#93C5FD',
  '--nb-mui-radio-checked': '#3B82F6',
  '--nb-mui-form-label': '#737373',
  '--nb-mui-form-label-checked': '#374151',

  // ── Font Family ──
  '--nb-font-primary': "'Roboto', sans-serif",
  '--nb-font-secondary': "'Poppins', sans-serif",
  '--nb-font-mono': "'Roboto Mono', 'Consolas', monospace",

  // ── Font Weights ──
  '--nb-font-light': '300',
  '--nb-font-normal': '400',
  '--nb-font-medium': '500',
  '--nb-font-semibold': '600',
  '--nb-font-bold': '700',

  // ── Line Heights ──
  '--nb-leading-tight': '1.2',
  '--nb-leading-snug': '1.3',
  '--nb-leading-normal': '1.4',
  '--nb-leading-relaxed': '1.5',
  '--nb-leading-loose': '1.6',

  // ── Font Sizes ──
  '--nb-text-xs': '10px',
  '--nb-text-sm': '11px',
  '--nb-text-base': '12px',
  '--nb-text-md': '13px',
  '--nb-text-lg': '14px',
  '--nb-text-xl': '16px',
  '--nb-text-2xl': '18px',
  '--nb-text-3xl': '20px',
  '--nb-text-4xl': '24px',
  '--nb-text-5xl': '28px',
  '--nb-text-6xl': '34px',

  // ── Primary Text Colors ──
  '--nb-text-primary': '#3B82F6',
  '--nb-text-secondary': '#374151',
  '--nb-text-tertiary': '#737373',
  '--nb-text-muted': '#9F9F9F',
  '--nb-text-white': '#FFFFFF',
  '--nb-text-black': '#000000',
  '--nb-text-title': '#22304B',

  // ── Semantic Text Colors ──
  '--nb-text-success': '#16A34A',
  '--nb-text-error': '#DC2626',
  '--nb-text-warning': '#EAB308',
  '--nb-text-info': '#3B82F6',
  '--nb-text-critical': '#EF4444',
  '--nb-text-currency': '#22C55E',

  // ── Observability Text Colors ──
  '--nb-text-cpu-limit': '#EF4444',
  '--nb-text-cpu-recommendation': '#16A34A',
  '--nb-text-cpu-requested': '#3B82F6',
  '--nb-text-cpu-usage': '#FFA500',
  '--nb-text-memory-limit': '#EF4444',
  '--nb-text-memory-recommendation': '#16A34A',
  '--nb-text-memory-requested': '#3B82F6',
  '--nb-text-memory-usage': '#FFA500',

  // ─────────────────────────────────────────────────────────────────────────
  // DS TOKENS (--ds-*) — canonical design system, SSR fallback parity.
  // Source of truth: app/design-system/shared/styles.css
  // New code MUST prefer these over --nb-*.
  // ─────────────────────────────────────────────────────────────────────────

  // Surfaces
  '--ds-background-100': '#ffffff',
  '--ds-background-200': '#fafafa',
  '--ds-background-300': '#f5f5f5',

  // Gray
  '--ds-gray-100': '#f2f2f2',
  '--ds-gray-200': '#ebebeb',
  '--ds-gray-300': '#e3e3e3',
  '--ds-gray-400': '#a8a8a8',
  '--ds-gray-500': '#8f8f8f',
  '--ds-gray-600': '#6f6f6f',
  '--ds-gray-700': '#171717',

  // Gray alpha
  '--ds-gray-alpha-100': 'rgba(0, 0, 0, 0.05)',
  '--ds-gray-alpha-200': 'rgba(0, 0, 0, 0.08)',
  '--ds-gray-alpha-300': 'rgba(0, 0, 0, 0.10)',
  '--ds-gray-alpha-400': 'rgba(0, 0, 0, 0.34)',
  '--ds-gray-alpha-500': 'rgba(0, 0, 0, 0.44)',
  '--ds-gray-alpha-600': 'rgba(0, 0, 0, 0.56)',
  '--ds-gray-alpha-700': 'rgba(0, 0, 0, 0.91)',

  // Blue
  '--ds-blue-100': '#f0f7ff',
  '--ds-blue-200': '#d6ebff',
  '--ds-blue-300': '#adcfff',
  '--ds-blue-400': '#5b9eff',
  '--ds-blue-500': '#2f7af0',
  '--ds-blue-600': '#0c64d6',
  '--ds-blue-700': '#0a4ea3',

  // Red
  '--ds-red-100': '#fff0f0',
  '--ds-red-200': '#ffd6d6',
  '--ds-red-300': '#ffadad',
  '--ds-red-400': '#ff6b6b',
  '--ds-red-500': '#e5484d',
  '--ds-red-600': '#c8323a',
  '--ds-red-700': '#9a1f25',

  // Amber
  '--ds-amber-100': '#fff8e0',
  '--ds-amber-200': '#ffeaa3',
  '--ds-amber-300': '#ffd158',
  '--ds-amber-400': '#f5b400',
  '--ds-amber-500': '#d99100',
  '--ds-amber-600': '#a66a00',
  '--ds-amber-700': '#6e4500',

  // Green
  '--ds-green-100': '#ebfaee',
  '--ds-green-200': '#c7f0d2',
  '--ds-green-300': '#8fe0a3',
  '--ds-green-400': '#46c168',
  '--ds-green-500': '#2ca84c',
  '--ds-green-600': '#1f8a3c',
  '--ds-green-700': '#135a27',

  // Teal
  '--ds-teal-50': '#ecfdfd',
  '--ds-teal-100': '#cff1f2',
  '--ds-teal-200': '#b8eef0',
  '--ds-teal-300': '#79dadc',
  '--ds-teal-400': '#2bb8bb',
  '--ds-teal-500': '#199a9d',
  '--ds-teal-600': '#0f7a7c',
  '--ds-teal-700': '#075052',

  // Purple
  '--ds-purple-100': '#f5f0ff',
  '--ds-purple-200': '#e2d3ff',
  '--ds-purple-300': '#c2a5ff',
  '--ds-purple-400': '#8a5cf6',
  '--ds-purple-500': '#6f3fe0',
  '--ds-purple-600': '#5527b8',
  '--ds-purple-700': '#361679',

  // Pink
  '--ds-pink-100': '#fff0f7',
  '--ds-pink-200': '#ffd1e3',
  '--ds-pink-300': '#ff9ec4',
  '--ds-pink-400': '#ee5697',
  '--ds-pink-500': '#d23a7c',
  '--ds-pink-600': '#a4225f',
  '--ds-pink-700': '#69143b',

  // Brand navy (Sidebar Dark, anchored at #1B2D4A)
  '--ds-brand-100': '#EEF1F6',
  '--ds-brand-200': '#D5DCE7',
  '--ds-brand-300': '#A4B0C5',
  '--ds-brand-400': '#6B7B9A',
  '--ds-brand-500': '#2A3D5A',
  '--ds-brand-600': '#1B2D4A',
  '--ds-brand-700': '#122035',

  // Brand yellow (Nudgebee Yellow, anchored at #FACF39)
  '--ds-yellow-100': '#FFFBEA',
  '--ds-yellow-200': '#FFF3C2',
  '--ds-yellow-300': '#FCE699',
  '--ds-yellow-400': '#FCDB6A',
  '--ds-yellow-500': '#FACF39',
  '--ds-yellow-600': '#E5B81F',
  '--ds-yellow-700': '#B58F12',

  // Type scale
  '--ds-text-caption': '11px',
  '--ds-text-caption-lh': '1.4',
  '--ds-text-small': '12px',
  '--ds-text-small-lh': '1.4',
  '--ds-text-body': '13px',
  '--ds-text-body-lh': '1.45',
  '--ds-text-body-lg': '14px',
  '--ds-text-body-lg-lh': '1.5',
  '--ds-text-title': '16px',
  '--ds-text-title-lh': '1.3',
  '--ds-text-heading': '20px',
  '--ds-text-heading-lh': '1.25',
  '--ds-text-display': '28px',
  '--ds-text-display-lh': '1.2',

  '--ds-font-weight-regular': '400',
  '--ds-font-weight-medium': '500',
  '--ds-font-weight-semibold': '600',

  '--ds-font-sans': "'Inter', 'Poppins', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  '--ds-font-mono': "'JetBrains Mono', 'Consolas', 'Monaco', 'Courier New', monospace",

  // Spacing
  '--ds-space-1': '4px',
  '--ds-space-2': '8px',
  '--ds-space-3': '12px',
  '--ds-space-4': '16px',
  '--ds-space-5': '24px',
  '--ds-space-6': '32px',
  '--ds-space-7': '48px',

  // Radius
  '--ds-radius-sm': '4px',
  '--ds-radius-md': '6px',
  '--ds-radius-lg': '8px',
  '--ds-radius-pill': '999px',

  // Motion
  '--ds-motion-micro': '120ms',
  '--ds-motion-panel': '180ms',
  '--ds-motion-ease': 'cubic-bezier(0.16, 1, 0.3, 1)',
};
