package api

import (
	"log/slog"

	"github.com/gin-gonic/gin"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	swaggerfiles "github.com/swaggo/files"
	ginswagger "github.com/swaggo/gin-swagger"

	_ "nudgebee/services/docs/swagger" // generated by `swag init`
)

func ConfigureRoutes(r *gin.Engine, tracer *trace.Tracer, meter *metric.Meter, logger *slog.Logger) {
	handleHasuraApis(r, tracer, meter, logger)
	handleHasuraCrons(r, tracer, meter, logger)
	handleHeathCheckApis(r, tracer, meter, logger)
	handleAuditApis(r, tracer, meter, logger)
	handleAuthzApis(r, tracer, meter, logger)
	handleCacheApis(r, tracer, meter, logger)
	handleMarketplaceEvents(r, tracer, meter, logger)
	handleMigrationApis(r, tracer, meter, logger)
	handleIntegrationApis(r, tracer, meter, logger)
	handlePublicWebhooksApis(r, tracer, meter, logger)
	handleEventRuleApis(r, tracer, meter, logger)
	handleHasuraTriageApis(r, tracer, meter, logger)
	handleExportApis(r, tracer, meter, logger)
	handleEntitlementApis(r, tracer, meter, logger)
	handleRelayApis(r, tracer, meter, logger)

	// OpenAPI spec — swag-generated docs merged with stub entries for every
	// other registered gin route, so the UI reflects 100% of the route table.
	r.GET("/openapi.json", mergedOpenAPIHandler(r))

	// Swagger UI: /swagger/index.html. Reads the merged spec above.
	// Auth bypassed for /swagger and /openapi.json in main.go.
	r.GET("/swagger/*any", ginswagger.WrapHandler(
		swaggerfiles.Handler,
		ginswagger.URL("/openapi.json"),
	))
}
