name: workflow-server CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - runbook-server/**
      - .github/workflows/workflow-server.yaml
      - deploy/kubernetes/workflow-server/**

jobs:
  app-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        go-version: ["1.26.x"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: ./runbook-server/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.9.0
          working-directory: ./runbook-server
          args: --timeout 20m
